#!/bin/bash

. "/usr/bin/variables"

printf "\n\n\n==============================================================\n"

echo "Setup Plexdrive"

printf "==============================================================\n\n\n"

plexdrive mount $plexdrive_options "${cloud_encrypt_dir}"
